# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_esp',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione Spagna'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_fra',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione Francese'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione Inglese'),
        ),
        migrations.AddField(
            model_name='post',
            name='titolo_esp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titolo Spagna:'),
        ),
        migrations.AddField(
            model_name='post',
            name='titolo_fra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titolo Francese:'),
        ),
        migrations.AddField(
            model_name='post',
            name='titolo_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titolo Inglese:'),
        ),
    ]
