# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.folder
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20160706_0635'),
        ('sito', '0002_auto_20160706_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100, verbose_name='Titolo:')),
                ('inizio', models.DateTimeField(verbose_name='inizio')),
                ('fine', models.DateTimeField(verbose_name='fine')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider')),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
                ('slider', image_cropping.fields.ImageRatioField('image', '1170x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Slider')),
                ('thumb', image_cropping.fields.ImageRatioField('image', '600x449', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Miniatura')),
                ('thumbdue', image_cropping.fields.ImageRatioField('image', '745x558', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Miniatura pagina dettaglio')),
                ('croplibero', image_cropping.fields.ImageRatioField('image', '595x335', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Ritaglio Libero')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('active', models.BooleanField(default=False, verbose_name='attiva')),
                ('slide', models.BooleanField(default=False, verbose_name='Mostra in Slide')),
                ('album', filer.fields.folder.FilerFolderField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Folder')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'News',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='carousel_home',
            field=models.ImageField(blank=True, null=True, upload_to='slider', verbose_name='Carosello in Home'),
        ),
        migrations.AddField(
            model_name='post',
            name='revolution_home',
            field=image_cropping.fields.ImageRatioField('slider_home', '1170x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='revolution home'),
        ),
        migrations.AddField(
            model_name='post',
            name='slider_home',
            field=models.ImageField(blank=True, null=True, upload_to='slider', verbose_name='Slider in Home'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumb_cinque',
            field=image_cropping.fields.ImageRatioField('image', '600x602', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='600x602px'),
        ),
        migrations.AlterField(
            model_name='post',
            name='impaginazione',
            field=models.CharField(blank=True, choices=[('width-and-small', '400x400'), ('width-and-height', '400x791'), ('width-and-height', '600x602'), ('width-and-long', '800x400'), ('width-and-big', '800x638')], max_length=200, null=True),
        ),
    ]
