# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0003_auto_20160728_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('titolo_uk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titolo Inglese:')),
                ('titolo_fra', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titolo Francese:')),
                ('titolo_esp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titolo Spagna:')),
                ('icona', models.CharField(blank=True, max_length=100, null=True, verbose_name='icona')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name_plural': 'Box',
            },
        ),
    ]
